# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'waskitalive' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for waskitalive
  platform :ios, '9.0'
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]
  
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'



  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

  pod 'react-native-mail', :path => '../node_modules/react-native-mail'

  pod 'Firebase/Analytics'

  pod 'Firebase/Core', '~> 6.13.0'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  
  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  target 'waskitaliveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  post_install do |installer|
    rnfirebase = installer.pods_project.targets.find { |target| target.name == 'RNFirebase' }
    rnfirebase.build_configurations.each do |config|
      config.build_settings['HEADER_SEARCH_PATHS'] = '$(inherited) ${PODS_ROOT}/Headers/Public/**'
    end
  end
  end

end

target 'waskitalive-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for waskitalive-tvOS

  target 'waskitalive-tvOSTests' do
    inherit! :search_paths
  end

end
